### ISSUE TITLE
Problem with iPad Mini Retina?

### ISSUE THREAD

**Issue by leecrossley** [leecrossley/cordova-plugin-pedometer#1]
http://ilee.co.uk/Core-Motion-Pedometer-with-Cordova/#comment-1715492946

**Comment by jgamedev** [comment]
I'm copying the information I posted on your blog  to this topic.

IPad Mini Retina:
pedometer.isDistanceAvailable returns false.
pedometer.startPedometerUpdates calls  onError with error message: 'CMErrorDomain error 104'. 

I was only able to dig up information on Google about error codes 102 and 105.
Haven't found anything regarding error code 104.

**Comment by mattblair** [comment]
(Note: I'm using CMPedometer directly in Objective-C, but the errors probably have the same origin.)

Code 104 indicates that no step or distance information is available. I see that when testing pedometer apps on iPhones which don't have an M7 or M8 chip, such as the 5, 4s, iPod Touch 5th Gen etc., and also the simulator. I'm not sure offhand if that's the same error returned when access to motion activity is denied.

It's my understanding that even iPads which have an M7 or M8 chip do not report step/distance data. Why? Not sure, and it's not well documented.

Another error in the CMErrorDomain which I've encountered is 107. I tracked that one down to a bug which was running a query with an endDate which was earlier than the startDate.

**Comment by leecrossley** [comment]
Thanks for your insight @mattblair. The safest bet for this plugin (and native implementations) is to [check the feature support](https://github.com/leecrossley/cordova-plugin-pedometer#check-feature-support) (e.g. `isDistanceAvailable` etc). If it's not supported, there's little else that can be done.

**Comment by eduardonunesp** [comment]
Sorry to comment at a closed issue, but I think there's a problem at isStepCountingAvailable,because in simulator succeeded to find the pedometer. But later it return the error `CMErrorDomain error 104` at `startPedometerUpdates`
