### ISSUE TITLE
Fetching Historical Pedometer Data

### ISSUE THREAD

**Issue by antsav** [leecrossley/cordova-plugin-pedometer#2]
Could you please add functionality to retrieve steps from Core Motion for certain dates range. 

`- queryPedometerDataFromDate:toDate:withHandler`

`
pedometer.getSteps({
  startDate : 
  endDate : 
}
function (success) {},
function (error) {}
)
`

https://developer.apple.com/library/prerelease/ios/documentation/CoreMotion/Reference/CMPedometer_class/index.html#//apple_ref/occ/cl/CMPedometer

**Comment by t0lkman** [comment]
:+1:

**Comment by leecrossley** [comment]
Please see the [readme](https://github.com/leecrossley/cordova-plugin-pedometer#historical-pedometer-data) for the correct usage to query historical pedometer data.
