### ISSUE TITLE
app just crash on ios 9.1

### ISSUE THREAD

**Issue by tunee** [leecrossley/cordova-plugin-pedometer#9]
when called the  pedometer.startPedometerUpdates(successHandler, onError) function, the apps just exit. its working on ios 8.4 with no problem. no step count on ipad as well

**Comment by leecrossley** [comment]
Did you check feature detection?

**Comment by tunee** [comment]
yerp, feature detection is functioning properly. Here is the error in xcode. **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[4]' . Its seem that   @"floorsAscended": pedometerData.floorsAscended and @"floorsDescended": pedometerData.floorsDescended return null value and cannot insert in the dictionary. 

The problem is temporary fixed by comment out this two line and the code is working correctly again. 

//  @"floorsAscended": pedometerData.floorsAscended,
 //                   @"floorsDescended": pedometerData.floorsDescended

This problem happen after upgrading to xcode 7.1
